### ISSUE TITLE
Breaks default highlighting.

### ISSUE THREAD

**Issue by dbauszus-glx** [WebReflection/vscode-literally-html#10]
Having this plugin enabled breaks other highlighting within the same file. The brackets are coloured with the [bracket pair colorizer plugin](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer).

![image](https://user-images.githubusercontent.com/22201617/52232082-8361ea00-28b3-11e9-91a0-f9a028f44b82.png)

With the plugin disabled I get to see highlights outside the literal. 

![image](https://user-images.githubusercontent.com/22201617/52232133-a4c2d600-28b3-11e9-9456-690e098d35e4.png)

**Comment by WebReflection** [comment]
> Having this plugin enabled breaks other highlighting within the same file.

or maybe it's the other way around?

anyway, I'm partially color blinded, I wouldn't even know how to be sure I've fixed this so please look somewhere else for HTML tags highlight if you need it to work with bracket pair colorizer plugin.
