### ISSUE TITLE
Support Prettier‑compatible `/* HTML */` comment prefix

### ISSUE THREAD

**Issue by ExE-Boss** [WebReflection/vscode-literally-html#13]
[**Prettier**](https://prettier.io) uses the `/* HTML */` comment prefix as a hint that a template string contains HTML markup when it can’t otherwise determine what the template string contains.

---

/cc @prettier/core @evilebottnawi @jf-1 @lydell

**Comment by WebReflection** [comment]
I can't even publish latest changes to vsce, but I also know nothing about vs code in general, so anything that is not in yet, or easy to change, won't likely land, 'cause I wouldn't know how.

**Comment by WebReflection** [comment]
OK, I've eventually managed to push the `node` part, that's something ... now, about prettier, I still wouldn't know what to do here, so I'll flag as _help wanted_, sure enough pretty much nobody will show up 😅 (but at least I've tried)

**Comment by ExE-Boss** [comment]
All&nbsp;you need&nbsp;to&nbsp;do is&nbsp;highlight template&nbsp;strings that&nbsp;follow a&nbsp;`/* HTML */`&nbsp;comment as&nbsp;being&nbsp;HTML.

## Example:
```js
const example = /* HTML */ `
	<div>${getHTML()}</div>
`;
```

**Comment by WebReflection** [comment]
does prettier put that also in between `html` or `svg` and the template literal content?

**Comment by ExE-Boss** [comment]
> does prettier put that also in between `html` or `svg` and the template literal content?

No, it&nbsp;only&nbsp;needs it&nbsp;for&nbsp;the&nbsp;likes of&nbsp;`unknownHtmlTag` (currently&nbsp;`html.node`, `html.for(…)`,&nbsp;etc.).

Without `/* HTML */` **Prettier** ends&nbsp;up&nbsp;formatting the&nbsp;`unknownHtmlTag` template&nbsp;tag as&nbsp;a&nbsp;normal template&nbsp;string.

**Comment by WebReflection** [comment]
this looks like a Prettier bug then, as it should allow custom definition of what's is known to produce from html template literals (which should be literally any tag function or anything used as tag).

I don't think I ever want `/* HTML */` comments on my way, so I am not sure I should do anything in here.

**Comment by ghost** [comment]
@WebReflection How can someone get syntax highlighting in an untagged template literal with your extension then ? If `/* HTML */` before the literal is not ok , is  having the literal inside of it to start with `<--!html-->` ok ?

**Comment by WebReflection** [comment]
I don't known, PR welcome

**Comment by WebReflection** [comment]
Added a **WARNING** in the README with suggested alternatives: https://github.com/WebReflection/vscode-literally-html/tree/master?tab=readme-ov-file#warning
