### ISSUE TITLE
Proposal: Make the Component Configureable via .vscode/settings.json

### ISSUE THREAD

**Issue by frank-dspeed** [WebReflection/vscode-literally-html#14]
"begin": "(?x)\\.*(?:[a-zA-Z]+\\.)?\\b(adopt|bind|bound|for|hyper|hyperHTML|html|raw|render|svg|view|viper|viperHTML|wire)\\b(?:\\([^\\)]*?\\))?(`)",

**Comment by WebReflection** [comment]
PR welcome, but also ... I don't understand what is this about.

**Comment by frank-dspeed** [comment]
this is the regex match code inside your component and it hold as you see a list of tags it should match for we could put that list optional in the .vscode/settings so the user or project settings then the people can configure that them self and this would not need to get updated to get extended for a extra case

**Comment by WebReflection** [comment]
Thanks for expanding on that. I am really not familiar with how VS Code works, so any PR welcome, thanks.

**Comment by WebReflection** [comment]
Added a **WARNING** in the README with suggested alternatives: https://github.com/WebReflection/vscode-literally-html/tree/master?tab=readme-ov-file#warning
