### ISSUE TITLE
Handle Generic Tagged Template Functions

### ISSUE THREAD

**Issue by EisenbergEffect** [WebReflection/vscode-literally-html#15]
Love this plugin and love the fact that it's being built in a library-agnostic way 😄 

On that note, our `html` tag accepts generics when used with TypeScript. For example:

```TypeScript
const template = html<MyElement>`
  some html goes here
`;
```

When the generic args (`<MyElement>`) are added, the plugin no longer recognizes the following string as HTML 😢 

Is this something that can easily be fixed? I'd be happy to make a contribution if you can point me to the right place.

Thanks!

**Comment by WebReflection** [comment]
due vs code market place absurd flow, I had to drop the previous version and upload from scratch the new one. This issue should've been solved.

**Comment by EisenbergEffect** [comment]
Thanks for addressing that so quick! 😄
