### ISSUE TITLE
Extension not avail to VSCodium users

### ISSUE THREAD

**Issue by drschwabe** [WebReflection/vscode-literally-html#17]
https://open-vsx.org/?search=vscode-literally-html

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by WebReflection** [comment]
I've "*literally*" just installed it on VS Codium (ArchLinux default code module) and it worked?

**Comment by WebReflection** [comment]
Added a **WARNING** in the README with suggested alternatives: https://github.com/WebReflection/vscode-literally-html/tree/master?tab=readme-ov-file#warning
