### ISSUE TITLE
Syntax highlighting breaks when a trigger word appears in a nested template string

### ISSUE THREAD

**Issue by y6nH** [WebReflection/vscode-literally-html#18]
Something else must have changed, since this has only appeared recently, but literally-html is the extension I have to disable to fix the problem.

When a trigger word such as "view", "html" or "raw" appears in a template string inside another template string, syntax highlighting doesn't work afterwards.

Here's a potted example:

```ts
const ok = `interpolated string ${`some normal words`}`;
const bad = `interpolated string ${`view`}`;
const afterwards = { formatting: "broken" };
```

![image](https://github.com/WebReflection/vscode-literally-html/assets/355120/cbf68a13-4f33-4189-b84c-6a4725117c9f)

**Comment by WebReflection** [comment]
I'm close to abandon this project as this one seems to work better by all means: https://marketplace.visualstudio.com/items?itemName=lehwark.htmx-literals

**Comment by WebReflection** [comment]
Added a **WARNING** in the README with suggested alternatives: https://github.com/WebReflection/vscode-literally-html/tree/master?tab=readme-ov-file#warning
