### ISSUE TITLE
Why can't I get highlighting with "svg" (framework agnostic?)

### ISSUE THREAD

**Issue by SMotaal** [WebReflection/vscode-literally-html#2]
https://github.com/WebReflection/vscode-literally-html/blob/49300402e02f258c371c6d96b4398caa6c1169ed/syntaxes/literally-html.json#L18

Can you please provide some mechanism for a configurable (or truly agnostic) alternative in par with the described features/goals.

So the following should somehow be supported:

```js

// When this is defined
const svg = (strings, ...values) =>
  normalize(String.raw(strings, ...values));

// The following should be highlighted
let content = svg`<svg></svg>`;

```

I'll leave the scope of determining how to activate tags (hint: already definable in ts/jsconfig's of the plugin). The only reason lit-html was not a generic extension was because they do not honour the settings in ts/jsconfig (even though they actually expose both html and svg tagged templates in their catchup reimplementation of your vision).

Cheers!

**Comment by WebReflection** [comment]
Not too fond of the tone used in this report and it looks like you are perfectly able to file a PR, right?

**Comment by SMotaal** [comment]
Sorry, not my intent at all, it's quite the opposite frankly (I am a huge fan of your ideas and was shocked at how lit-html repackaged it without proper credit) but my apologies anyway.

... As for PR-ing, I am not there yet in terms of an implementation strategy myself, but if we hash out the details I will be willing to dig into it as soon as I am off the clock.

**Comment by WebReflection** [comment]
fair enough ... my misunderstanding then.

so ... the RegExp needs a `svg` somewhere, I can do that.

This part ... I've no idea what is this about:

> I'll leave the scope of determining how to activate tags (hint: already definable in ts/jsconfig's of the plugin)

mind explaining imagining I don't ever TypeScript ever?

**Comment by SMotaal** [comment]
Well, I originally marked that line because I was wondering if it can be dynamically changed. My thought was if somehow the end-user of the plugin can alter this without having to recompile and publish (not a fan of that eco-system honestly) it would be a lot less taxing and you'd be spared from issues like this one.

According to [the upstream readme](https://github.com/Microsoft/typescript-lit-html-plugin#configuration) there are some configurable aspects that can be included in ts/jsconfig:

> 
> You can enable IntelliSense for other tag names by configuring `"tags"`:
> 
> ```json
> {
>   "compilerOptions": {
>     "plugins": [
>       {
>         "name": "typescript-lit-html-plugin",
>         "tags": [
>           "html",
>           "template"
>         ]
>       }
>     ]
>   }
> }
> ```
> 

So one is inclined to believe that the original through was to configure which tags would activate the highlighting but then implementation was either not possible or simply not done yet.

**Comment by WebReflection** [comment]
so, I think I've already published a version that should support `svg` ... mind trying ?

**Comment by SMotaal** [comment]
Perfect... So are you thinking of making it dynamic down the road?

**Comment by WebReflection** [comment]
I don't know much about VS extensions and this one works already fine for my needs.

I wish the original one would change the name so we could all enjoy a nice agnostic extension ... until that happens, I don't have time to waste here.

Every PR that will help improving it is welcome though.

Glad this change worked.

**Comment by SMotaal** [comment]
Until that point, I just realized that instead of adding more things into the RegEx we can simply define `tag.html = tag` then use `tag.html` to get syntax highlighting which is better than the problem-prone alternative of `var html = tag`.

Thanks!

**Comment by SMotaal** [comment]
I ended up here today as I was forced to doing some preemptive reflection [into my issues](https://github.com/search?l=&o=asc&p=3&q=author%3ASMotaal+is%3Aissue+created%3A%3E2014-06-01+author%3ASMotaal+updated%3A%3C2019-06-01&s=created&type=Issues) 🤣 

@WebReflection, thank you so much for being one of the few good examples on how to deal with the `wt?!` in the tone and manner I displayed on this issue, which was different and offensive. Where you rightfully must have been furious but you decided to nudge me to figure out if I need to do a better job next time. Because you had me pause long enough, I realized how far off I was in my communication efforts, and took time to untangle my side of things, to offer my genuine and sincere apology for what I did.

Cheers and Sincere Thanks!

**Comment by WebReflection** [comment]
Looks like I can't reply hidden/off topics comments but no worries, nothing
too bad happened there, yet I am not actively maintaining this extension as
it "just works" for my needs, but I still welcome PRs to improve it for
others too 👋
