### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by otbe** [WebReflection/vscode-literally-html#4]
Hi,

I tried to your fork to get highlighting & language support working in VSCode 1.25.0-insider and hyperhtml. Its somehoew broken for me, for example:
<img width="549" alt="bildschirmfoto 2018-06-25 um 13 11 31" src="https://user-images.githubusercontent.com/3391052/41847313-d4bb28b6-7879-11e8-8abf-5bad6bb85d96.png">
As you can see highlighting works for `hyper()/render()` but not for `html`, but language support only works for `html` and not for `hyper()/render()`.
![bildschirmfoto 2018-06-25 um 13 15 37](https://user-images.githubusercontent.com/3391052/41847361-06d67f3a-787a-11e8-8d1f-23bf74e84191.png)

For hyperHTML fns (bind,wire) highlighting is working but language support is completly broken. I tried you advice to add the plugin via jsconfig.json, but with the same result.

Any idea whats wrong?

Thanks!

**Comment by ExE-Boss** [comment]
Syntax highlighting only works for top level template literals (see&nbsp;issue&nbsp;https://github.com/WebReflection/vscode-literally-html/issues/3).

As for intellisense language support, that’s handled by [typescript&#x2011;lit&#x2011;html&#x2011;plugin](https://github.com/Microsoft/typescript-lit-html-plugin).

**Comment by ExE-Boss** [comment]
As for intellisense language support, that’s handled by [typescript&#x2011;lit&#x2011;html&#x2011;plugin](https://github.com/Microsoft/typescript-lit-html-plugin).
