### ISSUE TITLE
Support for template properties

### ISSUE THREAD

**Issue by st-schneider** [WebReflection/vscode-literally-html#5]
Can you add support for adding highlight support for structures like
```
{
  template: `
	<div></div>
  `
}
```
by extending the regex maybe like so
```
"begin": "(?x)\\.*(?:[a-zA-Z]+\\.)?(template:\\s|\\b(template:\\s|adopt|bind|bound|hyper|hyperHTML|html|raw|render|svg|view|wire)\\b)(?:\\([^\\)]*?\\))?(`)",
```

**Comment by frank-dspeed** [comment]
adding support for this pattern 
```js
//The patttern
: `.*`
```

also 

```js
//The patttern
= `.*`
```

**Comment by WebReflection** [comment]
PR welcome 👋

**Comment by WebReflection** [comment]
Added a **WARNING** in the README with suggested alternatives: https://github.com/WebReflection/vscode-literally-html/tree/master?tab=readme-ov-file#warning
