### ISSUE TITLE
Publish version 0.1.0 to the VSCode Marketplace

### ISSUE THREAD

**Issue by ExE-Boss** [WebReflection/vscode-literally-html#9]
Right now, the&nbsp;published version in&nbsp;the&nbsp;**VSCode&nbsp;Marketplace** is&nbsp;still&nbsp;0.0.5, whereas&nbsp;the&nbsp;latest version available in&nbsp;the&nbsp;repository is&nbsp;0.1.0.

**Comment by WebReflection** [comment]
I actually don't remember how to publish there .. I was hoping updating tags would've been enough ... 😅

**Comment by WebReflection** [comment]
I've tried ... not sure when/what/how if it's updated now

**Comment by WebReflection** [comment]
it says `0.1.0` now 🎉
